name: adb-reboot
slug: my_addon
startup: services
url: https://github.com/filipvh/ha-addon-adb-reboot
panel_icon: mdi:android
version: 1.0
description: ADB Reboot devices
host_network: true
init: false
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
boot: auto
schema:
  reboot:
    - host: str
      cron: str
options:
  reboot: []
